"use client";

import { forwardRef } from "react";
import Image from "next/image";
import type { Game, ChatMessage } from "./types";
import { moneyline } from "./utils";

interface ShareCardProps {
  mode: "daily" | "chat";
  headline: string;
  dailyMarkdown: string;
  selectedGame: Game | null;
  chatMessages: ChatMessage[];
}

const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(function ShareCard(
  { mode, headline, dailyMarkdown, selectedGame, chatMessages },
  ref,
) {
  return (
    <div
      aria-hidden="true"
      ref={ref}
      className="fixed left-[-9999px] top-[-9999px] z-0 w-[760px] bg-[#0a0e1a] p-0 text-sm"
    >
      {/* Top accent gradient */}
      <div className="h-1 bg-gradient-to-r from-[#00c853] via-[#00ff87] to-[#00c853]" />

      <div className="p-8">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-[#2a3852]/40 pb-5">
          <div className="flex items-center gap-3">
            <Image src="/lockin-logo.png" alt="LOCKIN" width={130} height={40} />
            <div className="rounded-full border border-[#00c853]/30 bg-[#00c853]/10 px-2.5 py-0.5 text-[10px] font-medium text-[#00c853]">
              AI-POWERED
            </div>
          </div>
          <div className="mono text-xs text-[#8b92a5]">lockinpicks.ai</div>
        </div>

        {/* Content */}
        {mode === "daily" ? (
          <div className="mt-6">
            <div className="mb-1 text-[10px] font-medium uppercase tracking-widest text-[#00c853]">Daily Edge</div>
            <div className="heading mb-3 text-2xl font-bold text-[#00ff87]">LOCKIN Daily Edge</div>
            <div className="mb-4 text-sm text-[#8b92a5]">{headline}</div>
            <div className="rounded-xl border border-[#2a3852]/30 bg-[#111829]/60 p-5">
              <p className="whitespace-pre-wrap leading-relaxed text-[#f5f5f3]">{dailyMarkdown}</p>
            </div>
          </div>
        ) : (
          <div className="mt-6">
            <div className="mb-1 text-[10px] font-medium uppercase tracking-widest text-[#00c853]">Match Insight</div>
            <div className="heading mb-3 text-2xl font-bold text-[#00ff87]">
              {selectedGame
                ? `${selectedGame.awayTeam} @ ${selectedGame.homeTeam}`
                : "LOCKIN Match Insight"}
            </div>
            {selectedGame && (
              <div className="mb-4 flex gap-3">
                <span className="mono rounded-lg border border-white/[0.06] bg-black/20 px-3 py-1.5 text-sm text-white">
                  {selectedGame.awayTeam} ML {moneyline(selectedGame.awayMoneyline)}
                </span>
                <span className="mono rounded-lg border border-white/[0.06] bg-black/20 px-3 py-1.5 text-sm text-white">
                  {selectedGame.homeTeam} ML {moneyline(selectedGame.homeMoneyline)}
                </span>
              </div>
            )}
            <div className="rounded-xl border border-[#2a3852]/30 bg-[#111829]/60 p-5">
              <p className="whitespace-pre-wrap leading-relaxed text-[#f5f5f3]">
                {chatMessages
                  .filter((item) => item.role === "assistant")
                  .slice(-1)
                  .map((msg) => msg.content)
                  .join("\n") || "No chat summary yet."}
              </p>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-6 flex items-center justify-between border-t border-[#2a3852]/30 pt-4">
          <span className="text-xs text-[#8b92a5]">Generated by LOCKIN &middot; AI-powered NBA analysis</span>
          <span className="rounded-full border border-[#ffd700]/25 bg-[#ffd700]/[0.06] px-2.5 py-0.5 text-[10px] font-medium text-[#ffd700]">
            lockinpicks.ai
          </span>
        </div>
      </div>
    </div>
  );
});

export default ShareCard;
