"use client";

import { forwardRef } from "react";
import Image from "next/image";
import type { Game, ChatMessage } from "./types";
import { moneyline } from "./utils";

interface ShareCardProps {
  mode: "daily" | "chat";
  headline: string;
  dailyMarkdown: string;
  selectedGame: Game | null;
  chatMessages: ChatMessage[];
}

const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(function ShareCard(
  { mode, headline, dailyMarkdown, selectedGame, chatMessages },
  ref,
) {
  return (
    <div
      aria-hidden="true"
      ref={ref}
      className="fixed left-[-9999px] top-[-9999px] z-0 w-[760px] bg-[#0a0e1a] p-0 text-sm"
    >
      <div className="h-1 bg-gradient-to-r from-[#0a0e1a] via-[#00c853] to-[#0a0e1a]" />

      <div className="p-8">
        <div className="flex items-center justify-between border-b border-white/10 pb-5">
          <div className="flex items-center gap-3">
            <Image src="/lockin-logo.png" alt="LOCKIN" width={130} height={40} />
          </div>
          <div className="mono text-xs text-[#8b92a5]">lockinpicks.com</div>
        </div>

        {mode === "daily" ? (
          <div className="mt-6">
            <div className="mb-1 text-[10px] font-medium uppercase tracking-widest text-[#00c853]">Tonight&apos;s Edge</div>
            <div className="heading mb-3 text-2xl font-bold text-[#f5f5f3]">LOCKIN Daily Edge</div>
            <div className="mb-4 text-sm text-[#8b92a5]">{headline}</div>
            <div className="rounded-xl border border-white/10 bg-white/[0.04] p-5">
              <p className="whitespace-pre-wrap leading-relaxed text-[#f5f5f3]">{dailyMarkdown}</p>
            </div>
          </div>
        ) : (
          <div className="mt-6">
            <div className="mb-1 text-[10px] font-medium uppercase tracking-widest text-[#00c853]">Match Insight</div>
            <div className="heading mb-3 text-2xl font-bold text-[#f5f5f3]">
              {selectedGame
                ? `${selectedGame.awayTeam} @ ${selectedGame.homeTeam}`
                : "LOCKIN Match Insight"}
            </div>
            {selectedGame && (
              <div className="mb-4 flex gap-3">
                <span className="mono rounded-lg border border-white/10 bg-white/[0.04] px-3 py-1.5 text-sm text-[#f5f5f3]">
                  {selectedGame.awayTeam} ML {moneyline(selectedGame.awayMoneyline)}
                </span>
                <span className="mono rounded-lg border border-white/10 bg-white/[0.04] px-3 py-1.5 text-sm text-[#f5f5f3]">
                  {selectedGame.homeTeam} ML {moneyline(selectedGame.homeMoneyline)}
                </span>
              </div>
            )}
            <div className="rounded-xl border border-white/10 bg-white/[0.04] p-5">
              <p className="whitespace-pre-wrap leading-relaxed text-[#f5f5f3]">
                {chatMessages
                  .filter((item) => item.role === "assistant")
                  .slice(-1)
                  .map((msg) => msg.content)
                  .join("\n") || "No assistant response is available for export yet."}
              </p>
            </div>
          </div>
        )}

        <div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4">
          <span className="text-xs text-[#8b92a5]">Generated by LOCKIN · NBA moneyline analysis</span>
          <span className="rounded-full border border-[#00c853]/20 bg-[#00c853]/[0.06] px-2.5 py-0.5 text-[10px] font-medium text-[#00c853]">
            lockin
          </span>
        </div>
      </div>
    </div>
  );
});

export default ShareCard;
